---
- name: Install Base Packages
  apt: "name={{ item }} state=present"
  with_items:
    - apt-transport-https
    - git
    - openssh-server
    - sudo

- name: Add debian backports.
  apt_repository:
    repo: "deb http://ftp.de.debian.org/debian jessie-backports main"
    state: present
    update_cache: yes

- name: Install OpenJDK 8
  apt:
    name: openjdk-8-jdk
    state: present
    default_release: jessie-backports

- name: Select OpenJDK 8 as default
  alternatives:
    name: java
    path: /usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/bin/java
