---
- hosts: jenkins
  become_user: sudo

  pre_tasks:
    - name: Update repository when older than 1 hour.
      apt: update_cache=yes cache_valid_time=3600

  tasks:
    - name: Install Base Packages
      apt: "name={{ item }} state=present"
      with_items:
        - apt-transport-https
        - git
        - openssh-server
        - openjdk-7-jdk
        - sudo

- name: Jenkins user configuration.
  hosts: jenkins
  become_user: sudo

  vars:
    jenkins_user_home: "/home/jenkins"

  # Once https://github.com/ansible/ansible/issues/13263 is fixed activate
  # the password prompt when a custom variable (change_pw ...) is set.
  vars_prompt:
    - name: "jenkins_user_password"
      prompt: "Enter the jenkins user password. Pressing enter will keep the password as is."
      default: ""
      confirm: yes
      private: yes

  tasks:
    - name: Specify the jenkins user with a custom home.
      user:
        name: jenkins
        home: "{{ jenkins_user_home }}"
        comment: Jenkins
        system: yes
        shell: /bin/bash

    - name: Change the password for the jenkins user.
      user:
        name: jenkins
        password: "{{ jenkins_user_password | password_hash('sha512') }}"
        update_password: always
      when:
        - jenkins_user_password != ""

    - name: Ensure jenkins users can reboot their host without sudo password.
      lineinfile:
        state: present
        dest: /etc/sudoers
        insertafter: "^# User privilege specification"
        regexp: "^jenkins\tALL=NOPASSWD: "
        line: "jenkins\tALL=NOPASSWD: /sbin/reboot"
        validate: "visudo -cf %s"


- hosts: jenkins_master
  become_user: sudo

  vars:
    jenkins_user_home: "/home/jenkins"
    jenkins_home: "{{ jenkins_user_home }}/jenkins"

  handlers:
    - name: restart jenkins
      service: "name=jenkins state=restarted"

  pre_tasks:
    - name: Update repository when older than 1 hour.
      apt: update_cache=yes cache_valid_time=3600

  tasks:
    - name: Add Key for Jenkins Debian Repository
      apt_key:
        url: https://pkg.jenkins.io/debian/jenkins.io.key
        state: present

    - name: Add Repository for Jenkins
      apt_repository:
        repo: deb https://pkg.jenkins.io/debian binary/
        state: present
        update_cache: yes

    - name: Install Jenkins
      apt: "name=jenkins state=present"
      environment:
        JENKINS_HOME: "{{ jenkins_home }}"

    - name: Change Jenkins Defaults
      ini_file:
        section: null
        dest: /etc/default/jenkins
        no_extra_spaces: yes
        backup: yes
        option: JENKINS_HOME
        value: "{{ jenkins_home }}"
      notify: restart jenkins

    - name: Ensure Jenkins is started and enabled on boot.
      service: name=jenkins state=started enabled=yes
