---
- hosts: jenkins
  become_user: sudo

  tasks:
    - name: Update repository when older than 1 hour.
      apt: update_cache=yes cache_valid_time=3600

    - name: Install Base Packages
      apt: "name={{ item }} state=present"
      with_items:
        - apt-transport-https
        - git
        - openssh-server
        - openjdk-7-jdk

- hosts: jenkins_master
  become_user: sudo

  vars:
    jenkins_user_home: "/home/jenkins"
    jenkins_home: "{{ jenkins_user_home }}/jenkins"

  handlers:
    - name: restart jenkins
      service: "name=jenkins state=restarted"

  tasks:
    - name: Add Key for Jenkins Debian Repository
      apt_key:
        url: https://pkg.jenkins.io/debian/jenkins.io.key
        state: present

    - name: Add Repository for Jenkins
      apt_repository:
        repo: deb https://pkg.jenkins.io/debian binary/
        state: present
        update_cache: yes

    - name: Specify Jenkins User with Custom Home
      user:
        name: jenkins
        home: "{{ jenkins_user_home }}"
        comment: Jenkins
        system: yes
        shell: /bin/bash

    - name: Install Jenkins
      apt: "name=jenkins state=present"
      environment:
        JENKINS_HOME: "{{ jenkins_home }}"

    - name: Change Jenkins Defaults
      ini_file:
        section: null
        dest: /etc/default/jenkins
        no_extra_spaces: yes
        backup: yes
        option: JENKINS_HOME
        value: "{{ jenkins_home }}"
      notify: restart jenkins

    - name: Ensure Jenkins is started and enabled on boot.
      service: name=jenkins state=started enabled=yes
