---
- hosts: jenkins_master
  become: yes

  # Once https://github.com/ansible/ansible/issues/13263 is fixed activate
  # the password prompt when a custom variable (change_pw ...) is set.
  vars_prompt:
    - name: "jenkins_user_password"
      prompt: "Enter the jenkins user password. Pressing enter will keep the password as is."
      default: ""
      confirm: yes
      private: yes

  roles:
    - master

- hosts: emulators
  become: yes

  roles:
    - emulator
