---
- hosts: jenkins_master
  become: yes

  pre_tasks:
    - name: Load the passwords file if present.
      include_vars:
        dir: "."
        files_matching: "passwords.yml"
      no_log: yes

  roles:
    - master

- hosts: emulators
  become: yes

  pre_tasks:
    - name: Load the passwords file if present.
      include_vars:
        dir: "."
        files_matching: "passwords.yml"
      no_log: yes

  roles:
    - emulator
