---
- name: Get installed architectures.
  command: dpkg --print-foreign-architectures
  register: architectures
  changed_when: False

- name: Enable multiarch, needed by Android SDK.
  command: dpkg --add-architecture i386
  when: architectures.stdout != "i386"

- name: Update repository when a new architecture was added.
  apt: update_cache=yes
  when: architectures.stdout != "i386"

- name: Install Android SDK dependencies.
  apt: name={{ item }} state=present
  with_items:
    - "libstdc++6:i386"
    - "libgcc1:i386"
    - "zlib1g:i386"
    - "libncurses5:i386"
    - qemu-kvm
    - libvirt-bin

- name: Add the catroid user to the KVM group, to have KVM support for the emulator.
  user:
    name: catroid
    groups: kvm
    append: yes

- name: Create the license directory.
  file:
    path: "{{ android_sdk_license_dir }}"
    state: directory
    recurse: yes
  become_user: catroid

- name: Create the android sdk licence file.
  copy:
    content: "\n8933bad161af4178b1185d1a37fbf41ea5269c55\n"
    dest: "{{ android_sdk_license_dir }}/android-sdk-license"
  become_user: catroid

- name: Create the android sdk preview licence file.
  copy:
    content: "\n84831b9409646a918e30573bab4c9c91346d8abd\n"
    dest: "{{ android_sdk_license_dir }}/android-sdk-preview-license"
  become_user: catroid
